version: '3.8'

services:
  api:
    image: dnxt/demos/demo-utilizador
    ports:
      - "8081:9090"
    networks:
      - learning_ntw
  keycloak:
    image: jboss/keycloak:4.8.3.Final
    restart: on-failure
    command:
      - "-b"
      - "0.0.0.0"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/config/"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    volumes:
      - ./config:/config/
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_ADDR=keycloak-db
      - DB_PORT=5432
      - DB_DATABASE=keycloakdb
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
    networks:
      - learning_ntw
  keycloak-db:
    image: postgres:10
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: demo
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - learning_ntw

volumes:
  pgdata:

networks:
  learning_ntw: