server:
  port: 9090
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      console.settings.trace: false
      spring.h2.console.settings.web-allow-others: false
  datasource:
    url: jdbc:h2:mem:memDb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    defer-datasource-initialization: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
keycloak:
  realm: Springboot-keycloak
  auth-server-url: http://localhost:8080/auth
  resource: utilizadores
  clientId: login-app
  secret: b4859226-8a50-44a6-bcc1-21f049d03a1c